name: CI/CD Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Stoppe alte Docker-Container
            docker compose -f ~/automated/portfolio/docker-compose.yml down || true

            # Wechsle ins App-Verzeichnis und aktualisiere den Code
            cd ~/automated/portfolio/app
            git pull origin main

            # Erstelle das Docker-Image
            docker build -t lenmp/portfolio:latest .

            # Starte Docker-Container neu
            cd ..
            docker compose -f ~/automated/portfolio/docker-compose.yml up -d --build
          EOF
